version: '3.1'
services:
  odoo:
    image: odoo:latest
    container_name: odoo
    depends_on: 
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo-data:/var/lib/odoo
    command: pip3 install pyjwt
  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - odoo-db:/var/lib/postgresql/data
volumes:
  odoo-data:
  odoo-db: